version: '3.4'

services:
  foodservice:
    image: ${DOCKER_REGISTRY-}foodservice
    build:
      context: .
      dockerfile: Dockerfile3

  orderservice:
    image: ${DOCKER_REGISTRY-}orderservice
    build:
      context: .
      dockerfile: Dockerfile2

  userservice:
    image: ${DOCKER_REGISTRY-}userservice
    build:
      context: .
      dockerfile: Dockerfile

  server:
    image: mcr.microsoft.com/mssql/server:2019-latest
    ports:
      - 1433:1433
    volumes:
      - ~/apps/mssql/data:/var/lib/mssqlql/data
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=Harimau@5
  